//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.HeroVirtualTabletop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Module.HeroVirtualTabletop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W &quot;+forward&quot;
        ///A &quot;+left&quot;
        ///S &quot;+backward&quot;
        ///D &quot;+right&quot;
        ///Z &quot;+down&quot;
        ///SPACE &quot;+up&quot;
        ///
        ///DOWN &quot;+lookup&quot;
        ///DOWNARROW &quot;+lookup&quot;
        ///LEFT &quot;+turnleft&quot;
        ///LEFTARROW &quot;+turnleft&quot;
        ///RIGHT &quot;+turnright&quot;
        ///RIGHTARROW &quot;+turnright&quot;
        ///UP &quot;+lookdown&quot;
        ///UPARROW &quot;+lookdown&quot;
        ///
        ///; &quot;+zoomin&quot;
        ///. &quot;+zoomout&quot;
        ///
        ///B &quot;bind_load_file b.txt&quot;
        ///C /nop
        ///H /nop
        ///delete /nop
        ///
        ///M &quot;move_npc&quot;
        ///
        ///X /nop&quot;
        ///
        ///F &quot;fly&quot;
        ///N &quot;noclip&quot;
        ///SHIFT+M &quot;popmenu maps&quot;
        ///SHIFT+N &quot;popmenu NPC&quot;
        ///.
        /// </summary>
        public static string required_keybinds {
            get {
                return ResourceManager.GetString("required_keybinds", resourceCulture);
            }
        }
    }
}
